const { createClient } = require('@supabase/supabase-js');
require('dotenv').config();

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseAnonKey = process.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  console.error("Erro: VITE_SUPABASE_URL ou VITE_SUPABASE_ANON_KEY não definidos no arquivo .env");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseAnonKey);

const items = [
  {
    id: "cf-alfa-transportes",
    nome: "Alfa Transportes LTDA",
    documento: "12.345.678/0001-90",
    telefone: "(91) 98888-1111",
    estado: "PA",
    relacionamento: "FOR",
    tipo: "Pessoa Jurídica",
    fazenda: "Av. Presidente Vargas",
    raw_data: {
      codigo: "F-2706260004",
      cnpjCpf: "12.345.678/0001-90",
      razaoSocial: "Alfa Transportes LTDA",
      nomeFantasia: "Alfa Transportes",
      relacionamento: "Fornecedor",
      inscricaoEstadual: "15.234.567-8",
      inscricaoMunicipal: "Isento",
      tipoPessoa: "Jurídica",
      fazendaPrincipal: "",
      contatoNome: "Mateus",
      contatoSobrenome: "Oliveira",
      contatoNomeContato: "Mateus Oliveira",
      contatoTelefone: "(91) 98888-1111",
      contatoWhatsapp: "Sim",
      contatoEmail: "contato@alfatransportes.com.br",
      contatoObservacoes: "Transportadora parceira",
      enderecoCep: "66060-110",
      enderecoLogradouro: "Av. Presidente Vargas",
      enderecoNumero: "1200",
      enderecoBairro: "Campina",
      enderecoPais: "Brasil",
      enderecoEstado: "Pará",
      enderecoCidade: "Belém",
      enderecoUf: "PA",
      enderecoComplemento: "Sala 301",
      financeiroCodBanco: "001",
      financeiroNomeBanco: "Banco do Brasil",
      financeiroAgencia: "1234-5",
      financeiroConta: "98765-4",
      financeiroTipoConta: "Conta Corrente",
      financeiroChavePix: "contato@alfatransportes.com.br",
      financeiroCondicaoPagamento: "30 Dias",
      financeiroLimiteCredito: "50.000,00",
      financeiroMoedaPadrao: "BRL - Real"
    }
  },
  {
    id: "cf-joao-marcelo",
    nome: "João Marcelo Santos",
    documento: "987.654.321-00",
    telefone: "(91) 98888-2222",
    estado: "PA",
    relacionamento: "CLI",
    tipo: "Pessoa Física",
    fazenda: "Rua das Flores",
    raw_data: {
      codigo: "C-2706260004",
      cnpjCpf: "987.654.321-00",
      razaoSocial: "João Marcelo Santos",
      nomeFantasia: "João M.",
      relacionamento: "Cliente",
      inscricaoEstadual: "Isento",
      inscricaoMunicipal: "Isento",
      tipoPessoa: "Física",
      fazendaPrincipal: "",
      contatoNome: "João",
      contatoSobrenome: "Santos",
      contatoNomeContato: "João Marcelo",
      contatoTelefone: "(91) 98888-2222",
      contatoWhatsapp: "Sim",
      contatoEmail: "joao.santos@gmail.com",
      contatoObservacoes: "Cliente para cria e recria",
      enderecoCep: "66825-000",
      enderecoLogradouro: "Rua das Flores",
      enderecoNumero: "45",
      enderecoBairro: "Centro",
      enderecoPais: "Brasil",
      enderecoEstado: "Pará",
      enderecoCidade: "Paragominas",
      enderecoUf: "PA",
      enderecoComplemento: "Casa",
      financeiroCodBanco: "260",
      financeiroNomeBanco: "Nubank",
      financeiroAgencia: "0001",
      financeiroConta: "12345678-9",
      financeiroTipoConta: "Conta Corrente",
      financeiroChavePix: "987.654.321-00",
      financeiroCondicaoPagamento: "À Vista",
      financeiroLimiteCredito: "2.000,00",
      financeiroMoedaPadrao: "BRL - Real"
    }
  },
  {
    id: "cf-norte-pegaso",
    nome: "Norte Pegaso Serviços LTDA",
    documento: "23.456.789/0001-55",
    telefone: "(91) 98888-3333",
    estado: "PA",
    relacionamento: "AMB",
    tipo: "Pessoa Jurídica",
    fazenda: "Av. Brasil",
    raw_data: {
      codigo: "C-2706260005",
      cnpjCpf: "23.456.789/0001-55",
      razaoSocial: "Norte Pegaso Serviços LTDA",
      nomeFantasia: "Norte Pegaso",
      relacionamento: "Ambos",
      inscricaoEstadual: "15.987.321-4",
      inscricaoMunicipal: "254303",
      tipoPessoa: "Jurídica",
      fazendaPrincipal: "",
      contatoNome: "Patricia",
      contatoSobrenome: "Gomes",
      contatoNomeContato: "Patricia Gomes",
      contatoTelefone: "(91) 98888-3333",
      contatoWhatsapp: "Sim",
      contatoEmail: "financeiro@nortepegaso.com.br",
      contatoObservacoes: "Prestador de serviços agro",
      enderecoCep: "68625-000",
      enderecoLogradouro: "Av. Brasil",
      enderecoNumero: "850",
      enderecoBairro: "Centro",
      enderecoPais: "Brasil",
      enderecoEstado: "Pará",
      enderecoCidade: "Bragança",
      enderecoUf: "PA",
      enderecoComplemento: "Galpão 02",
      financeiroCodBanco: "341",
      financeiroNomeBanco: "Itaú",
      financeiroAgencia: "4857",
      financeiroConta: "354166-8",
      financeiroTipoConta: "Conta Corrente",
      financeiroChavePix: "financeiro@nortepegaso.com.br",
      financeiroCondicaoPagamento: "15 Dias",
      financeiroLimiteCredito: "35.000,00",
      financeiroMoedaPadrao: "BRL - Real"
    }
  },
  {
    id: "cf-maria-eduarda",
    nome: "Maria Eduarda Lima",
    documento: "456.789.123-44",
    telefone: "(91) 98888-4444",
    estado: "PA",
    relacionamento: "CLI",
    tipo: "Pessoa Física",
    fazenda: "Rua São José",
    raw_data: {
      codigo: "C-2706260006",
      cnpjCpf: "456.789.123-44",
      razaoSocial: "Maria Eduarda Lima",
      nomeFantasia: "Duda Lima",
      relacionamento: "Cliente",
      inscricaoEstadual: "Isento",
      inscricaoMunicipal: "Isento",
      tipoPessoa: "Física",
      fazendaPrincipal: "",
      contatoNome: "Maria",
      contatoSobrenome: "Lima",
      contatoNomeContato: "Maria Eduarda",
      contatoTelefone: "(91) 98888-4444",
      contatoWhatsapp: "Sim",
      contatoEmail: "maria.lima@hotmail.com",
      contatoObservacoes: "Pecuarista recria",
      enderecoCep: "68743-000",
      enderecoLogradouro: "Rua São José",
      enderecoNumero: "132",
      enderecoBairro: "Nova Fronteira",
      enderecoPais: "Brasil",
      enderecoEstado: "Pará",
      enderecoCidade: "Castanhal",
      enderecoUf: "PA",
      enderecoComplemento: "Chácara",
      financeiroCodBanco: "237",
      financeiroNomeBanco: "Bradesco",
      financeiroAgencia: "7850",
      financeiroConta: "112233-4",
      financeiroTipoConta: "Conta Poupança",
      financeiroChavePix: "maria.lima@hotmail.com",
      financeiroCondicaoPagamento: "À Vista",
      financeiroLimiteCredito: "1.500,00",
      financeiroMoedaPadrao: "BRL - Real"
    }
  },
  {
    id: "cf-armazens-estacoes",
    nome: "Armazéns Estações & Comércio LTDA",
    documento: "34.567.890/0001-12",
    telefone: "(91) 98888-5555",
    estado: "PA",
    relacionamento: "FOR",
    tipo: "Pessoa Jurídica",
    fazenda: "Travessa Mauriti",
    raw_data: {
      codigo: "F-2706260005",
      cnpjCpf: "34.567.890/0001-12",
      razaoSocial: "Armazéns Estações & Comércio LTDA",
      nomeFantasia: "Armazéns Estações",
      relacionamento: "Fornecedor",
      inscricaoEstadual: "15.112.334-5",
      inscricaoMunicipal: "254302",
      tipoPessoa: "Jurídica",
      fazendaPrincipal: "",
      contatoNome: "Renato",
      contatoSobrenome: "Barros",
      contatoNomeContato: "Renato Barros",
      contatoTelefone: "(91) 98888-5555",
      contatoWhatsapp: "Não",
      contatoEmail: "vendas@estacoes.com.br",
      contatoObservacoes: "Fornecedor de insumos e nutrição",
      enderecoCep: "66085-220",
      enderecoLogradouro: "Travessa Mauriti",
      enderecoNumero: "350",
      enderecoBairro: "Marco",
      enderecoPais: "Brasil",
      enderecoEstado: "Pará",
      enderecoCidade: "Belém",
      enderecoUf: "PA",
      enderecoComplemento: "Galpão Comercial",
      financeiroCodBanco: "033",
      financeiroNomeBanco: "Santander",
      financeiroAgencia: "2235",
      financeiroConta: "998877-3",
      financeiroTipoConta: "Conta Corrente",
      financeiroChavePix: "34.567.890/0001-12",
      financeiroCondicaoPagamento: "30 Dias",
      financeiroLimiteCredito: "25.000,00",
      financeiroMoedaPadrao: "BRL - Real"
    }
  },
  {
    id: "cf-carlos-henrique",
    nome: "Carlos Henrique Abreu",
    documento: "654.321.987-10",
    telefone: "(91) 98888-6666",
    estado: "PA",
    relacionamento: "AMB",
    tipo: "Pessoa Física",
    fazenda: "Av. Carajás",
    raw_data: {
      codigo: "C-2706260007",
      cnpjCpf: "654.321.987-10",
      razaoSocial: "Carlos Henrique Abreu",
      nomeFantasia: "Carlos H.",
      relacionamento: "Ambos",
      inscricaoEstadual: "Isento",
      inscricaoMunicipal: "Isento",
      tipoPessoa: "Física",
      fazendaPrincipal: "",
      contatoNome: "Carlos",
      contatoSobrenome: "Abreu",
      contatoNomeContato: "Carlos Henrique",
      contatoTelefone: "(91) 98888-6666",
      contatoWhatsapp: "Sim",
      contatoEmail: "carlos.abreu@gmail.com",
      contatoObservacoes: "Compra e venda de gado",
      enderecoCep: "68550-000",
      enderecoLogradouro: "Av. Carajás",
      enderecoNumero: "230",
      enderecoBairro: "Centro",
      enderecoPais: "Brasil",
      enderecoEstado: "Pará",
      enderecoCidade: "Redenção",
      enderecoUf: "PA",
      enderecoComplemento: "Chácara Vale Verde",
      financeiroCodBanco: "033",
      financeiroNomeBanco: "Santander",
      financeiroAgencia: "2235",
      financeiroConta: "956877-3",
      financeiroTipoConta: "Conta Corrente",
      financeiroChavePix: "carlos.abreu@gmail.com",
      financeiroCondicaoPagamento: "15 Dias",
      financeiroLimiteCredito: "5.000,00",
      financeiroMoedaPadrao: "BRL - Real"
    }
  },
  {
    id: "cf-expresso-para",
    nome: "Expresso Pará Logística LTDA",
    documento: "45.678.901/0001-77",
    telefone: "(91) 98888-7777",
    estado: "PA",
    relacionamento: "FOR",
    tipo: "Pessoa Jurídica",
    fazenda: "Rodovia BR-316",
    raw_data: {
      codigo: "F-2706260006",
      cnpjCpf: "45.678.901/0001-77",
      razaoSocial: "Expresso Pará Logística LTDA",
      nomeFantasia: "Expresso Pará",
      relacionamento: "Fornecedor",
      inscricaoEstadual: "15.995.775-9",
      inscricaoMunicipal: "432373",
      tipoPessoa: "Jurídica",
      fazendaPrincipal: "",
      contatoNome: "Juliana",
      contatoSobrenome: "Costa",
      contatoNomeContato: "Juliana Costa",
      contatoTelefone: "(91) 98888-7777",
      contatoWhatsapp: "Sim",
      contatoEmail: "operacoes@expressopara.com.br",
      contatoObservacoes: "Parceiro logístico boiadeiro",
      enderecoCep: "67000-000",
      enderecoLogradouro: "Rodovia BR-316",
      enderecoNumero: "1500",
      enderecoBairro: "Guanabara",
      enderecoPais: "Brasil",
      enderecoEstado: "Pará",
      enderecoCidade: "Ananindeua",
      enderecoUf: "PA",
      enderecoComplemento: "Pátio Logístico",
      financeiroCodBanco: "756",
      financeiroNomeBanco: "Sicoob",
      financeiroAgencia: "3044",
      financeiroConta: "556677-8",
      financeiroTipoConta: "Conta Corrente",
      financeiroChavePix: "operacoes@expressopara.com.br",
      financeiroCondicaoPagamento: "30 Dias",
      financeiroLimiteCredito: "60.000,00",
      financeiroMoedaPadrao: "BRL - Real"
    }
  },
  {
    id: "cf-fernanda-rocha",
    nome: "Fernanda Rocha Martins",
    documento: "789.123.456-88",
    telefone: "(91) 98888-8888",
    estado: "PA",
    relacionamento: "CLI",
    tipo: "Pessoa Física",
    fazenda: "Rua Projetada",
    raw_data: {
      codigo: "C-2706260008",
      cnpjCpf: "789.123.456-88",
      razaoSocial: "Fernanda Rocha Martins",
      nomeFantasia: "Fê Rocha",
      relacionamento: "Cliente",
      inscricaoEstadual: "Isento",
      inscricaoMunicipal: "Isento",
      tipoPessoa: "Física",
      fazendaPrincipal: "",
      contatoNome: "Fernanda",
      contatoSobrenome: "Martins",
      contatoNomeContato: "Fernanda Martins",
      contatoTelefone: "(91) 98888-8888",
      contatoWhatsapp: "Sim",
      contatoEmail: "fernanda.martins@gmail.com",
      contatoObservacoes: "Cliente para terminação",
      enderecoCep: "68625-000",
      enderecoLogradouro: "Rua Projetada",
      enderecoNumero: "75",
      enderecoBairro: "Promissão",
      enderecoPais: "Brasil",
      enderecoEstado: "Pará",
      enderecoCidade: "Paragominas",
      enderecoUf: "PA",
      enderecoComplemento: "Chácara Recanto",
      financeiroCodBanco: "077",
      financeiroNomeBanco: "Banco Inter",
      financeiroAgencia: "0001",
      financeiroConta: "444555-6",
      financeiroTipoConta: "Conta Corrente",
      financeiroChavePix: "789.123.456-88",
      financeiroCondicaoPagamento: "À Vista",
      financeiroLimiteCredito: "3.000,00",
      financeiroMoedaPadrao: "BRL - Real"
    }
  },
  {
    id: "cf-technorte-sistemas",
    nome: "TechNorte Sistemas LTDA",
    documento: "56.789.012/0001-33",
    telefone: "(91) 98888-9999",
    estado: "PA",
    relacionamento: "AMB",
    tipo: "Pessoa Jurídica",
    fazenda: "Rua dos Pariquis",
    raw_data: {
      codigo: "C-2706260009",
      cnpjCpf: "56.789.012/0001-33",
      razaoSocial: "TechNorte Sistemas LTDA",
      nomeFantasia: "TechNorte",
      relacionamento: "Ambos",
      inscricaoEstadual: "15.778.000-1",
      inscricaoMunicipal: "330303",
      tipoPessoa: "Jurídica",
      fazendaPrincipal: "",
      contatoNome: "André",
      contatoSobrenome: "Moraes",
      contatoNomeContato: "André Moraes",
      contatoTelefone: "(91) 98888-9999",
      contatoWhatsapp: "Sim",
      contatoEmail: "suporte@technorte.com.br",
      contatoObservacoes: "Fornecedor de balanças e chips",
      enderecoCep: "66085-170",
      enderecoLogradouro: "Rua dos Pariquis",
      enderecoNumero: "430",
      enderecoBairro: "Batista Campos",
      enderecoPais: "Brasil",
      enderecoEstado: "Pará",
      enderecoCidade: "Belém",
      enderecoUf: "PA",
      enderecoComplemento: "Conjunto 12",
      financeiroCodBanco: "104",
      financeiroNomeBanco: "Caixa Econômica",
      financeiroAgencia: "0330",
      financeiroConta: "778899-0",
      financeiroTipoConta: "Conta Corrente",
      financeiroChavePix: "suporte@technorte.com.br",
      financeiroCondicaoPagamento: "15 Dias",
      financeiroLimiteCredito: "40.000,00",
      financeiroMoedaPadrao: "BRL - Real"
    }
  },
  {
    id: "cf-rafael-augusto",
    nome: "Rafael Augusto Pereira",
    documento: "121.654.987-22",
    telefone: "(91) 98888-0000",
    estado: "PA",
    relacionamento: "CLI",
    tipo: "Pessoa Física",
    fazenda: "Av. Nazaré",
    raw_data: {
      codigo: "C-2706260010",
      cnpjCpf: "121.654.987-22",
      razaoSocial: "Rafael Augusto Pereira",
      nomeFantasia: "Rafa Pereira",
      relacionamento: "Cliente",
      inscricaoEstadual: "Isento",
      inscricaoMunicipal: "Isento",
      tipoPessoa: "Física",
      fazendaPrincipal: "",
      contatoNome: "Rafael",
      contatoSobrenome: "Pereira",
      contatoNomeContato: "Rafael Augusto",
      contatoTelefone: "(91) 98888-0000",
      contatoWhatsapp: "Não",
      contatoEmail: "rafael.pereira@gmail.com",
      contatoObservacoes: "Cliente novo",
      enderecoCep: "68700-000",
      enderecoLogradouro: "Av. Nazaré",
      enderecoNumero: "300",
      enderecoBairro: "Centro",
      enderecoPais: "Brasil",
      enderecoEstado: "Pará",
      enderecoCidade: "Capanema",
      enderecoUf: "PA",
      enderecoComplemento: "Apto 104",
      financeiroCodBanco: "260",
      financeiroNomeBanco: "Nubank",
      financeiroAgencia: "0001",
      financeiroConta: "222333-4",
      financeiroTipoConta: "Conta Salário",
      financeiroChavePix: "rafael.pereira@gmail.com",
      financeiroCondicaoPagamento: "À Vista",
      financeiroLimiteCredito: "1.000,00",
      financeiroMoedaPadrao: "BRL - Real"
    }
  }
];

async function seed() {
  console.log(`Iniciando inserção de ${items.length} cadastros de clientes/fornecedores no Supabase...`);
  const { error } = await supabase.from('clientes_fornecedores').upsert(items);
  if (error) {
    console.error("Erro na inserção dos registros:", error.message);
    process.exit(1);
  }
  console.log("Sucesso: 10 registros de cadastros importados com sucesso!");
  process.exit(0);
}

seed();
